// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jwrTbggFxYGg2J5Z7e7kjr
// Component: wbMIVl9fXxkQ
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import BaseCard from "../../BaseCard" // plasmic-import: iNAkhDWaZXsp/component
import Bullet from "../../Bullet" // plasmic-import: 2iCIjF9Y6NHD/component
import Button from "../../Button" // plasmic-import: 58aE5A8cv3Bo/component
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_proadject_com.module.css" // plasmic-import: jwrTbggFxYGg2J5Z7e7kjr/projectcss
import * as sty from "./PlasmicPlan.module.css" // plasmic-import: wbMIVl9fXxkQ/css

export const PlasmicPlan__VariantProps = new Array()

export const PlasmicPlan__ArgProps = new Array(
  "price",
  "name",
  "description",
  "children"
)

function PlasmicPlan__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <BaseCard
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    >
      <div className={classNames(projectcss.all, sty.freeBox__mAtbg)}>
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__nblwG)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Basic",
            value: args.name,
            className: classNames(sty.slotTargetName),
          })}

          {p.renderPlasmicSlot({
            defaultContents: (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ut9Ar
                )}
              >
                {"$10"}
              </div>
            ),

            value: args.price,
          })}

          {p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__v0Agt)}
              >
                <Bullet
                  className={classNames("__wab_instance", sty.bullet__fpsmr)}
                />

                <Bullet
                  className={classNames("__wab_instance", sty.bullet__vsYSw)}
                />

                <Bullet
                  className={classNames("__wab_instance", sty.bullet__eZSE)}
                />
              </p.Stack>
            ),

            value: args.description,
          })}

          <div className={classNames(projectcss.all, sty.freeBox__cw6Ca)}>
            {p.renderPlasmicSlot({
              defaultContents: (
                <Button
                  className={classNames("__wab_instance", sty.button__q34Ey)}
                  color={"outlineBlue"}
                >
                  {"Get started"}
                </Button>
              ),

              value: args.children,
            })}
          </div>
        </p.Stack>
      </div>
    </BaseCard>
  )
}

const PlasmicDescendants = {
  root: ["root"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPlan__ArgProps,
      internalVariantPropNames: PlasmicPlan__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicPlan__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicPlan"
  } else {
    func.displayName = `PlasmicPlan.${nodeName}`
  }
  return func
}

export const PlasmicPlan = Object.assign(
  // Top-level PlasmicPlan renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicPlan
    internalVariantProps: PlasmicPlan__VariantProps,
    internalArgProps: PlasmicPlan__ArgProps,
  }
)

export default PlasmicPlan
/* prettier-ignore-end */
